import Head from "next/head";
import design from "../public/design.png";
import code from "../public/code.png";
import consulting from "../public/consulting.png";
import { useState } from 'react';
import { Hero, Navbar, Services, Card, Portfolio, Contact, Footer } from "./components";

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Ouday Fatteh</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar setDarkMode={setDarkMode} darkMode={darkMode} />
      <main className="bg-white pt-40 px-10 md:px-20 lg:px-40 dark:bg-gray-900 transition ease-in-out delay-150">
        <section className=" min-h-screen">

          <Hero />
        </section>
        <section>
          <Services />
          <div className="lg:flex gap-10">
            <Card image={design} title="Beautiful Designs" />
            <Card image={code} title="Clean and Well Documented Code" />
            <Card image={consulting} title="24/7 Support" />
          </div>
        </section>
        <section>
          <Portfolio />
        </section>
        <section>
          <Contact />
        </section>
      </main>
      <Footer />
    </div>
  );
}
